name: responsive_flutter
description: A new Flutter project.
version: 1.0.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  adaptive_navigation: ^0.0.9
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
